name: CI_CD

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Container
        run: docker build -t drone-server:latest .
        
      - name: Start Containers
        run: docker-compose -f "drone.yaml" up -d
        
      - name: Install dependecies
        run: pip install pymongo
        
      - name: Run Tests
        run: python tests/test.py
        
      - name: Stop containers
        if: always()
        run: docker-compose -f "drone.yaml" down
        
        
